### ISSUE TITLE
Project #2: Visualizing contents of the Information Management Code Registry

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/Hackathon-Central-2019#1]
Visualizing contents of the Information Management Code Registry to provide users an understanding of the types of software packages it contains, and to provide software developers an understanding of where coverage is lacking and where additional packages need to be added or new ones developed.

[The Information Management Code Registry Portal](http://imcr.ontosoft.org/#list)

[The IM Controlled Vocabulary](http://vocab.lternet.edu/vocab/registry/)

**Comment by ktoddbrown** [comment]
I like the idea of selecting/filtering key features and then preforming a cluster analysis to group the available software. We could also look for gaps in the feature permutations but that's going to be more an analysis than a visual.

**Comment by clnsmth** [comment]
Great ideas @ktoddbrown. Both visualizations and non-visualized analytical outputs are welcome. Really anything that helps understanding of IMCR contents would be useful.

What information does the user community want? What information does the developer community want? Do these use cases require an interactive application or would a static report suffice?

**Comment by clnsmth** [comment]
We did not pursue this project. It remains a viable project.
