### ISSUE TITLE
metajam fails to read data and metadata from EDI or LTER data repositories

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/Hackathon-Central-2019#13]
Hey folks I've prototyped `read_data_archived()` for reading DataONE member node data and metadata into R for use with our visualization tools and have encountered a few issues that I will get to work on ASAP!

1. `metajam` fails to download any data package from the EDI or LTER member nodes. This is very unexpected. I've forked a version of `metajam` for which I'll develop solutions to these issues and which will be one of our R package dependencies until the `metajam` maintainers integrate our solutions to their master branch.
2. `metajam` does not read data tables with more than one header line. I'll develop a solution to this with the same implementation plans as above.

In the mean time, the first example data package listed in the header of the `read_data_archived()` function loads successfully (an Arctic Data Center package) and should be used until I can get the bug patches developed.

**Comment by atn38** [comment]
Colin,
I've read in LTER data packages before with metajam, so I'm surprised.
Considering that it reads mostly EML for now, this is a big gap.

If the fix proves to be too much time, there is a stopgap solution to get
at attribute metadata: the function `get_attributes` from the EML R
package. metajam uses this under the hood and as far as I remember does not
add anything to its output. We'd need to download and read in the data
independently as well, but it might prove more feasible.

**Comment by brunj7** [comment]
Hi guys,

metajam should handle EDI and PASTA, so not sure what has changed. Please let me know if you find something @clnsmth. The error seems to point to the `check_version` function. Try to restart your session just in case.

Regarding headers, metajam is a wrapper around other R functions to read files in. It uses `read_csv` by default, so you can use the`skip` argument. See here for more details: https://brunj7.github.io/metajam-presentations/metajam-demo.html#single_dataset_-_with_header

**Comment by clnsmth** [comment]
Hi @atn38 and @brunj7. The EDI/LTER issue was related to classification of PASTA+ evaluation reports (.xml) as "DATA" and therefore attempted to read as tabular data. The reports are really package level metadata. I've implemented a fix in my `metajam` fork and will be submitting a pull request or two at the end of the hackathon. Thanks for the support @brunj7.

**Comment by clnsmth** [comment]
Issue 1 listed above has been fixed.

**Comment by clnsmth** [comment]
Issue 2 can be addressed by the recommendations of @brunj7.
