### ISSUE TITLE
Project R package name

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/Hackathon-Central-2019#14]
What's a good name for the project R package? [Here are some guidelines.](http://r-pkgs.had.co.nz/package.html)

**Comment by CoastalPlainSoils** [comment]
Unfortunately my favorite one I have come up with is taken: visualize

but I have these other ideas which appear to be available...
envision
graphme
graphit
plotnow
ediplot
plotz
glimpse

**Comment by atn38** [comment]
Not a name, but it'd be cool if the package tagline is "visualize the DOI"
:)

**Comment by clnsmth** [comment]
metajamViewer
dataPackageViewer
dataPackageExplorer

**Comment by ktoddbrown** [comment]
sedatr (Suitability Evaluator of DATa-packages in R)
sedatpacr (Suitability Evaluator of DATa-PACkages in R)
seguir (Suitability Evaluator GUI for R)

**Comment by clnsmth** [comment]
[Link to suggested package naming convention in ggplotgui issues.](https://github.com/IMCR-Hackathon/ggplotgui/issues/9)

**Comment by jhp7e** [comment]
datavue
datashot (like snapshot)
datapreview 

(also added individually in the other issue chain)
