### ISSUE TITLE
Project #1: Visualizing datasets

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/Hackathon-Central-2019#2]
Visualize a dataset to inform fitness for use, perhaps using metadata to inform the variables to plot and the types of plots to generate.

**Comment by jhp7e** [comment]
How far can we go using 1) only the information about an R data frame, or 2) using the R data frame information PLUS additional information from EML (data domain, attribute description, units) to identify possible useful diagnostic graphs for evaluating data for fitness-for-use and quality assurance AND/OR develop an interactive application that will permit users to rapidly generate the desired visualizations for themselves?

**Comment by atn38** [comment]
+1 for using data PLUS information from EML.

**Comment by lkuiucsb** [comment]
@jhp7e I can see there are two major components here, read data and plot data. For reading in data, I envision there will be at least three levels of read-data processes: 1. read in tabular data without any additional input from the user. 2. read in tabular data and use user-defined column attributes (categorical or numerical variables, or grouping factors). 3. read in data and EML information together, then use domain and unit nodes to assign column attribute (assuming EML is well documented). For data that have not been archived, we go with the first two scenarios (hopefully the second one). If the data have the EML document, we can and should take advantage of the EML (e.g. read in attribute label and unit for axis labeling). 

For plot data, there are at least four levels of auto-generating figures we can do using the code: a. plot all possible y-x figures, with restrictions such as y has to be numerical columns. Data from all three scenarios above can be used for this, the easiest code but at least 50% figures are useless. b. user define interested variables, and the code generates all possible combinations of the y-x plot. This improves the usefulness of the figures. Data from the second and third scenarios could be used in this. c. the user defines all the axis and grouping factor, using the interactive plot (e.g. R Shiny) and figures will be popped up, one at a time.  Data from the second and third scenarios could be used for this plotting d. Very specific figures (such as MNDS plot or cluster analysis) required for journal publications and high-level statistical analysis. I think we (code hackathon) only get to this level if there are individuals who are interested in their own data analysis.

From the b and c described above, we should be able to diagnose fitness-for-use, missing data, number range, some simple trends from a list of generated figures. For the code to be helpful for more than 50% of the people/datasets, I would not want to get caught in the minutia of each dataset.

**Comment by clnsmth** [comment]
We focused on visualizing the contents of data frames, largely without the information supplied by a corresponding metadata record. This enables visual exploration of a dataset that did not yet have metadata associated with it (a desired feature). Value added content can be supplied by the metadata record if it exists. This enhancement has been added to the project road map.
