### ISSUE TITLE
Prototyping EML plotting app

### ISSUE THREAD

**Issue by wetlandscapes** [IMCR-Hackathon/Hackathon-Central-2019#4]
One idea for visualizing EML information:
![xml_shiny_gui](https://user-images.githubusercontent.com/18599142/56852184-1f105e80-68d5-11e9-9c10-9353be313008.png)

**Comment by clnsmth** [comment]
Looks great @wetlandscapes! 

I like the coercion options. Could add "Download code" (suggested in #5) in place of "Download data" and "Download metadata" as these services are offered by the data repositories from which the data would be ingested.

**Comment by clnsmth** [comment]
This was a helpful sketch. The actual UI was an extension of a forked ggplot GUI app.
